FROM bdsmaneger/node_image
user root

# Java
RUN apt-get update && \
apt-get -y install openjdk-8-jdk-headless && \
apt-get clean && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
java -version

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

#  Android
ENV ANDROID_SDK_URL=https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip \
ANDROID_BUILD_TOOLS_VERSION=30.0.3 \
ANT_HOME=/usr/share/ant \
MAVEN_HOME=/usr/share/maven \
GRADLE_HOME=/usr/share/gradle \
ANDROID_SDK_ROOT=/opt/android
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/android/cmdline-tools/bin:/opt/android/platform-tools:/opt/android/build-tools/30.0.3:/usr/share/ant/bin:/usr/share/maven/bin:/usr/share/gradle/bin
WORKDIR /opt
RUN apt -qq update && \
apt -qq install -y wget curl maven ant gradle

RUN mkdir android && cd android && \
wget -O tools.zip ${ANDROID_SDK_URL} && \
unzip tools.zip && rm tools.zip

RUN mkdir /root/.android && touch /root/.android/repositories.cfg && \
while true; do echo 'y'; sleep 2; done | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" && \
while true; do echo 'y'; sleep 2; done | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platforms;android-25" "platforms;android-26" "platforms;android-27" && \
while true; do echo 'y'; sleep 2; done | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platforms;android-28" "platforms;android-29" "platforms;android-30" && \
while true; do echo 'y'; sleep 2; done | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "extras;android;m2repository" "extras;google;google_play_services" "extras;google;instantapps" "extras;google;m2repository" && \
while true; do echo 'y'; sleep 2; done | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "add-ons;addon-google_apis-google-22" "add-ons;addon-google_apis-google-23" "add-ons;addon-google_apis-google-24" "skiaparser;1"

RUN chmod a+x -R $ANDROID_SDK_ROOT && \
chown -R root:root $ANDROID_SDK_ROOT && \
rm -rf /opt/android/licenses && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
apt autoremove -y && \
apt clean && \
mvn -v && gradle -v && java -version && ant -version

RUN apt update && apt install -y curl gnupg2 lsb-release && \
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
apt-key fingerprint 1655A0AB68576280 && \
export VERSION=node_14.x && \
export DISTRO="$(lsb_release -s -c)" && \
echo "deb https://deb.nodesource.com/$VERSION $DISTRO main" | tee /etc/apt/sources.list.d/nodesource.list && \
echo "deb-src https://deb.nodesource.com/$VERSION $DISTRO main" | tee -a /etc/apt/sources.list.d/nodesource.list && \
apt update && apt install -y nodejs && \
node -v && npm -v && \
npm install -g yarn && \
yarn -v && \
apt clean && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV CORDOVA_VERSION=10.0.0

WORKDIR /tmp


RUN npm i -g --unsafe-perm cordova@${CORDOVA_VERSION} && \
cordova -v && \
cd /tmp && \
cordova create myApp com.myCompany.myApp myApp && \
cd myApp && \
cordova plugin add cordova-plugin-camera --save && \
cordova platform add android --save && \
cordova requirements android && \
cordova build android --verbose && \
rm -rf /tmp/myApp

ENV DOCKER_IMAGE=true
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt upgrade -y