# bdsmaneger/node_image
FROM ubuntu:latest
USER root
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
apt-get -y install curl wget git zsh libnss3 libatk-bridge2.0-0 gconf-service libasound2 libatk1.0-0 libc6 \
libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 \
libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 \
libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils libgbm-dev git wget curl sudo && \
curl -fsSL https://deb.nodesource.com/setup_current.x | bash - && \
apt install -y nodejs && npm install -g -f npm && \
rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/* /tmp/*
ENV DOCKER_IMAGE="true"
ARG USERNAME=node
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN apt-get update && apt-get purge -y imagemagick imagemagick-6-common && \
wget https://raw.githubusercontent.com/microsoft/vscode-dev-containers/master/containers/javascript-node/.devcontainer/library-scripts/common-debian.sh -O /tmp/vcode-common-debian.sh && \
bash /tmp/vcode-common-debian.sh "true" "${USERNAME}" "${USER_UID}" "${USER_GID}" "true" && \
npm install -g eslint && \
npm cache clean --force > /dev/null 2>&1 && \
apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /root/.gnupg /tmp/library-scripts /tmp/*